/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TokenLocker {
      
    export type LockStruct = {id: BigNumberish, token: AddressLike, owner: AddressLike, amount: BigNumberish, unlockTime: BigNumberish, withdrawn: boolean}

    export type LockStructOutput = [id: bigint, token: string, owner: string, amount: bigint, unlockTime: bigint, withdrawn: boolean] & {id: bigint, token: string, owner: string, amount: bigint, unlockTime: bigint, withdrawn: boolean }
  
    }

  export interface TokenLockerInterface extends Interface {
    getFunction(nameOrSignature: "PROTOCOL_FEE" | "createLock" | "feeRecipient" | "getLock" | "getUserLockCount" | "getUserLocks" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LockCreated" | "LockWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'PROTOCOL_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'createLock', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLock', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserLockCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserLocks', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'PROTOCOL_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserLockCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserLocks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace LockCreatedEvent {
      export type InputTuple = [lockId: BigNumberish, token: AddressLike, owner: AddressLike, amount: BigNumberish, unlockTime: BigNumberish];
      export type OutputTuple = [lockId: bigint, token: string, owner: string, amount: bigint, unlockTime: bigint];
      export interface OutputObject {lockId: bigint, token: string, owner: string, amount: bigint, unlockTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockWithdrawnEvent {
      export type InputTuple = [lockId: BigNumberish, token: AddressLike, owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [lockId: bigint, token: string, owner: string, amount: bigint];
      export interface OutputObject {lockId: bigint, token: string, owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TokenLocker extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenLocker;
    waitForDeployment(): Promise<this>;

    interface: TokenLockerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PROTOCOL_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createLock: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, unlockTime: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getLock: TypedContractMethod<
      [lockId: BigNumberish, ],
      [TokenLocker.LockStructOutput],
      'view'
    >
    

    
    getUserLockCount: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserLocks: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [lockId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PROTOCOL_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createLock'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, unlockTime: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getLock'): TypedContractMethod<
      [lockId: BigNumberish, ],
      [TokenLocker.LockStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getUserLockCount'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserLocks'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [lockId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LockCreated'): TypedContractEvent<LockCreatedEvent.InputTuple, LockCreatedEvent.OutputTuple, LockCreatedEvent.OutputObject>;
getEvent(key: 'LockWithdrawn'): TypedContractEvent<LockWithdrawnEvent.InputTuple, LockWithdrawnEvent.OutputTuple, LockWithdrawnEvent.OutputObject>;

    filters: {
      
      'LockCreated(uint256,address,address,uint256,uint256)': TypedContractEvent<LockCreatedEvent.InputTuple, LockCreatedEvent.OutputTuple, LockCreatedEvent.OutputObject>;
      LockCreated: TypedContractEvent<LockCreatedEvent.InputTuple, LockCreatedEvent.OutputTuple, LockCreatedEvent.OutputObject>;
    

      'LockWithdrawn(uint256,address,address,uint256)': TypedContractEvent<LockWithdrawnEvent.InputTuple, LockWithdrawnEvent.OutputTuple, LockWithdrawnEvent.OutputObject>;
      LockWithdrawn: TypedContractEvent<LockWithdrawnEvent.InputTuple, LockWithdrawnEvent.OutputTuple, LockWithdrawnEvent.OutputObject>;
    
    };
  }