/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { FeeRejector, FeeRejectorInterface } from "../../TestHelpers.sol/FeeRejector.js";

  const _abi = [
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5060ed8061001b5f395ff3fe6080604052366041576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401603890609b565b60405180910390fd5b5f5ffd5b5f82825260208201905092915050565b7f6665652072656a656374656400000000000000000000000000000000000000005f82015250565b5f6087600c836045565b91506090826055565b602082019050919050565b5f6020820190508181035f83015260b081607d565b905091905056fea26469706673582212205a3b55a73ebd202c1ecaa44153efdcd5a2ca0c73f4ddbb0e1e9193492c8712e064736f6c634300081c0033";

  
      type FeeRejectorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: FeeRejectorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class FeeRejector__factory extends ContractFactory {
    
      constructor(...args: FeeRejectorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<FeeRejector & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): FeeRejector__factory {
      return super.connect(runner) as FeeRejector__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): FeeRejectorInterface {
      return new Interface(_abi) as FeeRejectorInterface;
    }
    
    override attach(address: string | Addressable): FeeRejector {
      return super.attach(address) as FeeRejector;
    }
  static connect(address: string, runner?: ContractRunner | null): FeeRejector {
      return new Contract(address, _abi, runner) as unknown as FeeRejector;
    }
  }

  
  