/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IERC20Approver, IERC20ApproverInterface } from "../../TestHelpers.sol/IERC20Approver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "spender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IERC20Approver__factory {
    static readonly abi = _abi;
    static createInterface(): IERC20ApproverInterface {
      return new Interface(_abi) as IERC20ApproverInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IERC20Approver {
      return new Contract(address, _abi, runner) as unknown as IERC20Approver;
    }
  }
  