/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITokenLocker, ITokenLockerInterface } from "../../TestHelpers.sol/ITokenLocker.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "unlockTime",
        "type": "uint256"
      }
    ],
    "name": "createLock",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class ITokenLocker__factory {
    static readonly abi = _abi;
    static createInterface(): ITokenLockerInterface {
      return new Interface(_abi) as ITokenLockerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITokenLocker {
      return new Contract(address, _abi, runner) as unknown as ITokenLocker;
    }
  }
  